dotenv: .env

compiler:
  solc:
    version: "0.8.17"
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"

networks:
  default: development
  development:
    gas_limit: auto

